config/routes.rb
Rails.application.routes.draw do
  resources :categories, except: :show
  resources :products, path: '/'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products, dependent: :restrict_with_exception
end

app/models/product.rb
class Product < ApplicationRecord
    include PgSearch::Model
    pg_search_scope :search_full_text, against: {
        title: 'A',
        description: 'B'
    }
    has_one_attached :photo 
    validates :title, presence: true
    validates :description, presence: true
    validates :price, presence: true

    belongs_to :category
end



app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    around_action :switch_locale

    def switch_locale(&action)
      I18n.with_locale(locale_from_header, &action)
    end
  
    private
  
    def locale_from_header
      request.env['HTTP_ACCEPT_LANGUAGE']&.scan(/^[a-z]{2}/)&.first
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all.order(name: :asc)
  end


  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url(@category), notice: t('.created')}
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url(@category), notice: t('.updated') }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: t('.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.order(name: :asc).load_async
    @products = Product.with_attached_photo.order(created_at: :desc).load_async

    if params[:category_id]
      @products = @products.where(category_id: params[:category_id])
    end

    if params[:min_price].present?
      @products = @products.where("price >= ?", params[:min_price])
    end

    if params[:max_price].present?
      @products = @products.where("price <= ?", params[:max_price])
    end

    if params[:query_text].present?
      @products = @products.search_full_text(params[:query_text])
    end
  end

  def show
    product
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path, notice: t('.created')
    else 
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    product
  end

  def update
    if product.update(product_params)
      redirect_to products_path, notice: t('.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    product.destroy

    redirect_to products_path, notice: t('.destroyed'), status: :see_other
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price, :photo, :category_id)
  end

  def product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <%= category.name %>
  <%= link_to t('.edit'), edit_category_path(category)%>
  <%= link_to t('.delete'), category_path(category), data: {
        turbo_method: :delete,
        turbo_confirm: t('common.confirm')
    }%>


</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% @category.errors.full_messages.each do |error|%>
      <div>
          <%=error%>
      </div>
  <%end%>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1><%= t('.title')%></h1>

<%= render "form", category: @category %>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/categories/index.html.erb
<h1><%= t('.title')%></h1>

<div>
<%= render partial: 'category', collection: @categories%>
</div>

<%= link_to t('.new'), new_category_path %>

app/views/categories/new.html.erb
<h1><%= t('.title')%></h1>

<%= render "form", category: @category %>

<div>
  <%= link_to t('common.back'), categories_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LaTiendecita</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%=  render 'shared/flash' %>
    <%=  render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/products/_category.html.erb
<%= link_to products_path(category_id: category.id), class: 'category' do %>
  <%= category.name %>
<% end %>

app/views/products/_form.html.erb
<%= form_with model: @product do |form|%>
    <% @product.errors.full_messages.each do |error|%>
        <div>
            <%=error%>
        </div>
    <%end%>
    <div>
        <%= form.label :title%>
        <%= form.text_field :title%>
    </div>

    <div>
        <%= form.label :description%>
        <%= form.text_area :description%>
    </div>

    <div>
        <%= form.label :price%>
        <%= form.number_field :price%>
    </div>

    <div>
        <%= form.label :category_id%>
        <%= form.collection_select :category_id, Category.all.order(name: :asc), :id, :name%>
    </div>

    <div>
        <%= form.label :photo%>
        <%= form.file_field :photo%>
    </div>

    <%= form.submit%>
<%end%>

app/views/products/_product.html.erb
<%= link_to product_path(product), class: 'product', 'data-turbo-frame': '_top' do %>
    <h2><%= product.title %></h2>
    <%= image_tag product.photo, width: 100 if product.photo.attached? %>
    <span><%= product.price %>$</span>
<% end %>

app/views/products/edit.html.erb
<h1><%=t('.title')%></h1>

<%= render 'form'%>

app/views/products/index.html.erb
<%=turbo_frame_tag 'categories' do%>
    <h1><%=t('.title')%></h1>

    <%= form_with url: products_path, method: :get do |form|%>
        <%= form.text_field :query_text, placeholder: t('.query_text'), 
        onChange: 'this.form.requestSubmit()', value: params[:query_text]%>
        <%= form.number_field :min_price, placeholder: t('.min_price'), 
        onChange: 'this.form.requestSubmit()', value: params[:min_price]%>
        <%= form.number_field :max_price, placeholder: t('.max_price'), 
        onChange: 'this.form.requestSubmit()', value: params[:max_price]%>
    <%end%>

    <%= link_to t('.all'), products_path%>

    <%= render partial: 'category', collection: @categories%>

    <%= render partial: 'product', collection: @products%>
<%end%>

app/views/products/new.html.erb
<h1><%=t('.title')%></h1>

<%= render 'form'%>

app/views/products/show.html.erb
<h1 class='title'><%=@product.title%></h1>

<%= image_tag @product.photo, width: 200 if @product.photo.attached?%>

<p class='description'><%=@product.description%></p>

<span class='price'><%=@product.price%>$</span>

<div>
    <%= link_to 'Editar producto', edit_product_path(@product)%>
</div>

<div>
    <%= link_to 'Eliminar producto', product_path(@product), data: {
        turbo_method: :delete,
        turbo_confirm: t('common.confirm')
    }%>
</div>

app/views/shared/_flash.html.erb
<%= notice%>
<%= alert%>

app/views/shared/_header.html.erb
    <%= link_to products_path do %>
        <h1>La Tiendecita</h1>
    <%end%>

    <div>
        <%= link_to t('.add'), new_product_path%>
    </div>
    <div>
        <%= link_to t('.categories'), categories_path%>
    </div>